/**
 * 上游 GodotMCP 工具中文描述表(自动生成,勿手改)。
 * 来源:plugin/godot-mcp-unified/server/docs/tool-reference/README.zh-CN.md
 * (上游 npm run docs:tools:zh 从 src/registration/catalogue.ts 生成)。
 * 离线门面/在线精确面共用:zhPrompt 开启时按工具名查本表取中文说明。
 */
export const UPSTREAM_TOOL_ZH: Readonly<Record<string, string>> = {
  editor_save_scene : "保存当前编辑中的场景。可选的 file_path 会触发“另存为”。",
  scene_open : "将场景（.tscn / .scn）作为当前编辑场景打开。仅支持 res://；文件不存在时返回 NOT_FOUND。",
  project_get_settings : "列出 ProjectSettings 的键和值。可选前缀过滤。匹配 `/password|token|secret|key/i` 的键会被丢弃（MVP 过滤器）。",
  node_inspect : "检查编辑场景节点；传 property 读取单值，省略时返回经过筛选的属性视图。",
  node_set_property : "设置编辑场景中的一个或多个节点属性；channel='runtime' 时设置运行中游戏的单个属性。",
  node_set_script : "给节点附加或解除 .gd/.cs 脚本，并返回脚本公开的导出属性。",
  node_manage : "对编辑场景树执行结构性节点操作。action: rename — 需要 new_name。action: reparent — 需要 new_parent_path，可选 keep_global_transform（默认 true）。action: reorder — 需要 new_index（从 0 开始的同级索引）。action: duplicate — 可选 new_name、parent_path、properties（例如 {position:{x,y}} 的覆盖值）。",
  capture_screenshot : "使用同一响应契约捕获运行中游戏或编辑器视口；运行时捕获需要活动的游玩测试。",
  runtime_inspect_node : "一次读取运行中节点的引擎属性、脚本变量或两者。",
  log_read : "读取编辑器或游戏输出；auto 优先读取实时运行时，并回退到编辑器侧崩溃缓存。",
  game_start : "启动游玩测试。默认阻塞直到运行时就绪；wait_for_runtime:false 会在不阻塞的情况下启动。scene_path:'main'|'current'（默认）|res://path。if_running:'return' 用于幂等模式。",
  game_stop : "停止当前播放的场景（幂等 — 如果没有运行中的场景则返回 was_running:false）。无参数。",
  input_simulate : "向运行中的游戏注入输入。events：单个 {event_type, event_data?, delay_before_ms?, delay_after_ms?} 表示一个动作，或表示动作序列的数组（相比多次调用，优先一次调用传入多个事件）。类型：key|mouse_button|mouse_motion|action|click|click_node|send_text。click 是组合操作：通过 push_input 按下 + 延迟 50ms + 释放（不操作 OS 焦点/光标定位；可安全并行）。click_node 接收 {node_path} — 调用 grab_focus，并在 BaseButtons 上发出 pressed（无需猜测坐标）。send_text 通过 push_input 合成逐字符键盘事件，将字符串输入聚焦的文本字段（或 event_data.node_path 指定的 Control），并触发设置 .text 时会跳过的真实 text_changed/text_submitted 信号。send_text 的 event_data：text（必需）、node_path?（先聚焦的 Control）、submit?（追加 Enter）；返回 focus_target、focus_source、text_changed、text_after（秘密字段会脱敏）、chars_sent 以及提示。鼠标坐标模式：- position：{x, y} — 原始视口/屏幕坐标（默认），用于 UI 元素（按钮、菜单）。- world_position：{x, y} — 游戏世界坐标，通过画布变换自动转换（考虑相机偏移和缩放），用于点击游戏内的特定位置。鼠标事件通过 push_input（position + global_position）路由，以进行 CanvasLayer/GUI 命中测试 — 不操作 OS 焦点/光标定位，可安全并行。返回每个事件的诊断信息。",
  scene_get_tree : "返回当前编辑场景的节点树；返回路径可直接传给其他编辑器工具。",
  scene_create_node : "在父节点下创建 class_name 指定的节点。支持引擎类和用户定义的 class_name 类。幂等：发生冲突时为 'returned'，全新创建时为 'created'。示例：class_name: \"CharacterBody2D\", parent_path: \".\", node_name: \"Player\"",
  scene_delete_node : "删除指定路径（NodePath）的节点。拒绝删除编辑场景根节点。",
  scene_create : "在 file_path 创建 .tscn。根名称 = 文件名在 '.' 之前的部分。root_type 默认为 Node。幂等结果：created|returned|replaced。if_exists：return|fail|replace。之后使用 scene_open 进行编辑。",
  scene_query : "按 class、group、name 和属性条件搜索场景树，结果有界并支持分页。",
  script_check : "离线验证 GDScript 并返回结构化诊断；跨文件检查使用 lsp_diagnostics 的 project scope。",
  animation_player_control : "驱动运行中游戏的 AnimationPlayer。operation：play|pause|stop|seek。可选 animation_name（play）或 time（seek）。返回操作后的状态。",
  runtime_time_control : "控制运行中游戏的时间以进行确定性游玩测试：冻结、解冻、检查状态、推进精确帧数，或推进至有界谓词变为 true 的 step_until。",
  signal_list : "列出节点上的信号。include_connections=true 会添加目标（{target_path, method_name, flags}）。flags & 2 = CONNECT_PERSIST（保存于 .tscn）。",
  signal_manage : "连接或断开信号（编辑器时间，CONNECT_PERSIST — 保存于 .tscn，保存/加载后仍保留）。连接操作幂等（冲突时 status 为 'returned'）。",
  signal_emit : "在节点上发出 signal_name，可选 args。channel='editor'（默认，编辑中的场景）或 channel='runtime'（运行中的游戏）。",
  animation_keyframe : "在已有动画的轨道上添加/删除关键帧。动画必须已经存在；action='add' 只会自动创建轨道。在完全相同时间点的重复项上保持幂等。",
  animation_get_keys : "列出 AnimationPlayer 轨道上的键：{ time, value, transition }。只读；不会自动创建轨道。",
  animationtree_edit : "配置 AnimationTree 状态机：设置根节点、添加/删除节点和过渡，或设置属性。",
  animationtree_list : "列出 AnimationTree 状态机的结构：根类型、节点和过渡。只读；不会产生变更。",
  input_map_edit : "新增/移除 InputMap action，或绑定/解绑键盘、鼠标和手柄事件。",
  folder_create : "在 res:// 路径创建目录（递归创建 — 父目录会自动创建）。幂等：全新创建时 status 为 created，已存在时返回已有对象。",
  resource_load : "加载 res:// 资源并返回 { class, path, properties, metadata }。会裁剪大型字段（image、mesh_arrays）；Texture2D 的大小会放入 metadata。",
  resource_write : "写入/创建 .tres/.res 资源。文件存在时更新属性；文件不存在时需要 'type'（类名）才能创建。对于 TileSet，请改用 tileset_create（它会处理图集和物理设置）。",
  asset_query : "列出编辑器索引中的项目资产，或读取一个资产的正向依赖。",
  asset_import : "把外部路径或 base64 二进制素材安全导入 res://，并触发 EditorFileSystem 扫描。",
  project_delete : "通过对应的类型安全路径删除 res:// 文件、目录、场景、脚本或资源；支持仅预演。",
  scene_close : "按 file_path 关闭已打开的场景标签页。会丢弃未保存的编辑 — 先使用 editor_save_scene 保存。最后一个标签页关闭时自动创建空场景。未打开时返回 NOT_FOUND。需要 Godot 4.5+。",
  user_data_read : "读取 user:// 文件的有界窗口，或列出一个 user:// 目录。",
  save_write : "写入 user:// 文件。非幂等。创建父目录。拒绝插件内部路径。",
  save_delete : "删除 user:// 文件。文件不存在时返回 NOT_FOUND。拒绝插件内部路径。",
  scene_diff : "将之前的场景树快照与另一个快照比较（省略 'after' 时与当前编辑场景比较）。返回 { changed, diff, added, removed }。",
  scene_instantiate : "在 parent_path 下的 scene_path 处实例化 PackedScene。单项模式：名称冲突时静默返回。批量模式：传入 instances 数组，以带变换的方式生成 N 个副本。单项：scene_path: \"res://coin.tscn\", parent_path: \".\", as_name: \"Coin\"；批量：scene_path: \"res://coin.tscn\", parent_path: \".\", instances: [{name:\"Coin1\",position:{x:100,y:200},properties:{coin_value:5}}, ...]",
  editor_sync : "刷新外部修改的项目文件，并等待 EditorFileSystem 完成扫描和导入。",
  tilemap_read_cells : "读取 TileMapLayer（4.3+）或已弃用的 TileMap 中已放置的瓦片数据。返回单元格坐标、source_id、atlas_coords。上限 500 个单元格。支持分页：returned、total_cells、has_more。无游标 — 使用 region/source_id 缩小范围以获取更多结果。",
  tilemap_set_cells : "在 TileMap 或 TileMapLayer 上批量设置单元格。返回 cells_written + cells_unchanged。source_id:-1 会清除单元格。批量矩形填充请使用 'regions'（比逐个列出单元格高效得多）。",
  tileset_create : "从纹理创建 TileSet .tres。生成带整瓦片矩形碰撞的图集瓦片（物理默认启用）。返回 source_id + 网格尺寸 — 将其与 tilemap_set_cells 一起使用。",
  tileset_add_source : "向已有 TileSet 添加图集源。为纹理中的每个网格单元格自动创建瓦片。返回新的 source_id。",
  tileset_remove_source : "从 TileSet 移除图集源。这会删除该源的全部瓦片数据。",
  tileset_add_alternative : "为基础瓦片创建替代瓦片变体（翻转、旋转、重新着色）。",
  tileset_remove_alternative : "从基础瓦片移除替代瓦片变体。",
  tileset_setup_layers : "配置 TileSet 图层：地形集（带命名地形）、自定义数据层，以及物理/导航/遮挡图层数量。",
  tileset_edit : "批量编辑 atlas tiles 的 physics、terrain、navigation、visuals 或 custom data。",
  theme_edit : "创建或修改 Godot Theme 资源（.tres）。为任意控件类型批量编辑颜色、常量、字体、字体大小、图标和样式盒。",
  layer_names_set : "设置物理/渲染层名称。category：2d_physics|2d_render|3d_physics|3d_render。layers：{1:'Ground', 2:'Player', …}（键为 1-32）。",
  layer_names_get : "读取已命名的物理/渲染层。仅返回名称非空的层。",
  path2d_edit_curve : "编辑 Path2D 节点的 Curve2D — 使用贝塞尔控制柄设置、添加或移除点。用于巡逻路线、移动平台、投射物曲线和摄像机轨道。",
  collision_from_texture : "根据 Sprite2D 的纹理 alpha 自动生成 CollisionPolygon2D。使用 BitMap 描摹不透明区域。用于平台游戏地形、角色碰撞箱和不规则形状。",
  scene_create_3d : "在编辑场景父节点下创建 3D primitive、WorldEnvironment、灯光或摄像机。",
  procedural_edit_gradient : "创建/编辑 Gradient 资源（.tres）。使用偏移设置颜色停靠点，添加/移除点。用于粒子、天空和视觉效果。",
  procedural_edit_curve : "创建/编辑 Curve 资源（.tres）。使用带切线的控制点设置缓动、衰减和值映射。",
  procedural_edit_noise : "创建/编辑 FastNoiseLite 资源（.tres）。配置噪声类型、分形、细胞噪声和域扭曲以进行程序化生成。",
  scene_create_inherited : "从基础场景创建继承场景（.tscn）— Godot 的预制体变体模式。写入最小 TSCN 文本，适用于所有 4.2-4.7 版本。",
  audiobus_edit : "管理音频总线：添加/移除总线，设置音量/发送/独奏/静音，添加/移除效果。bus_name 优先于 bus_index。效果类型可以是完整类名（AudioEffectReverb）或后缀（Reverb）。",
  audiobus_list : "列出所有音频总线及其音量/发送/独奏/静音状态和每条总线的效果。只读的总线布局快照。",
  spriteframes_create : "从显式帧纹理或 spritesheet 网格创建 SpriteFrames。",
  spriteframes_edit : "编辑已有 SpriteFrames 资源：添加/移除动画，添加/移除/重新排序帧，调整 fps/loop。'list' 返回所有动画。",
  particles_create : "创建 GPU 粒子系统（2D/3D），提供预设：fire、smoke、sparks、rain、snow、explosion、magic、dust。支持内联 color_ramp/scale_curve/alpha_curve。一次调用替代 7+ 个手动步骤。",
  navigation_edit : "编辑 NavigationRegion2D 多边形轮廓：设置全部轮廓、添加/移除单个轮廓、清除或烘焙导航网格。AI 寻路设置所需。",
  lsp_diagnostics : "对单个文件或整个项目运行 GDScript LSP 诊断；项目范围调用成本较高。",
  lsp_symbols : "列出 .gd/.gdshader 文件中的所有符号（函数、变量、类、信号）。结构化树 — 比读取完整源代码更节省。",
  lsp_hover : "获取特定位置处一个符号的类型签名和文档。用于针对性类型检查，不用于批量探索。",
  lsp_completion : "获取某个位置的补全。针对性查询使用 limit=5 以节省令牌。仅在需要发现可用 API 时调用。",
  lsp_navigate : "从一个源码位置查找符号定义或项目内的全部引用。",
  debug_inspect : "读取调试器会话状态或列出 GDScript 断点。",
  debug_set_breakpoint : "在脚本编辑器的指定文件和行设置或清除断点。仅限 GDScript（.gd）文件。",
  debug_continue : "调试器在断点处暂停时恢复执行。如果未处于断点暂停状态则失败。",
  classdb_query : "搜索 Godot 引擎/用户类，或读取一个类的继承、属性、方法、信号和常量。",
  project_set_setting : "写入 ProjectSettings 键，并通过 ProjectSettings.save 持久化。拒绝 mcp_toolkit/*、mcp/* 和 editor/* 前缀。返回 previous_value。执行更新（无 status）。",
  autoload_manage : "管理项目 autoload 单例（GameManager、AudioManager 等）。写入 project.godot；下次启动游戏时生效。action: register — 需要 name + script_path。action: unregister — 需要 name。action: list — 返回全部单例。",
  node_groups : "管理节点组成员关系。组是 Godot 标准的游戏对象标记和查询方式（例如 'coins'、'enemies'）。单项模式：node_path + group（add/remove/list 必需 node_path）。批量模式：entries 数组中的 {node_path, group} 携带每项路径，并忽略顶层 node_path/group。action: add — 需要 group。action: remove — 需要 group。action: list — 返回所有组（仅单项模式）。",
  control_set_layout : "一次调用为 Control 节点设置锚点预设和可选边距。使用 set_anchors_and_offsets_preset()。返回 final_rect。",
  scene_spatial_map : "当前场景的空间布局：每个节点的世界位置、边界（2D Rect2 / 3D AABB）、大小，以及计算出的重叠/间隙/包含关系。放置或移动节点前调用以寻找空闲空间。支持分页：returned、total_nodes、has_more。无游标 — 使用 subtree/class/region/radius 缩小范围，或提高 max_nodes 以获取更多结果。",
  execute_code : "危险：在 editor 或 runtime 通道计算 GDScript 表达式；仅在类型化工具无法表达操作时使用。",
  node_call_method : "在编辑场景节点上使用参数调用方法（仅编辑器可用；运行时节点使用 execute_code）。",
}
